#Variable file explanation:

#To do: Please change the $something in these file to your specification

---
#this is the passwd to become sudo on the remote host for using virt-install commands
#Please change the $passwd to your own.
pass:
  - ansible_become_pass=oakgal

#this is the information you need to run virt-install command
#You can configure to suit your need
#Note: For centos 6.5 and below, ISO must be fixed with the following link in order to kickstart
#http://forum.centos-webpanel.com/installation/solution-for-centos-6-6-minimal-kvm-guest-installation/
#Tested with Centos 6.5 and confirmed working with the fixed iso

#The location is where the iso will be located and highly suggested this location is consisted on VM hosts
#extra_args:
#	      ks stand for kickstart file. This file has to be avalible on the network for the VM to
#       download during the installation process. Highly suggested that you group these kickstart templates on an http host.
#       kickstart will do the installation process as you specify in this file.
#       Warning: kickstart can failed if proper setups are not given and it is hard to detected when you are using the virt-install command with ansible playbook. Usually the VM will be taking quite a lot of time during the installation reaching a roadblock. Best practice is to test
#       virt-install command with serial console option (remove graphics vnc or no graphics option)
#       and see the installation process go through to make sure. Only then use this file as a
#       template.
#       The test ks files can be found on trac kickstart documentation on operation section.

# Replace by prompt comments:
#                  These commented variables can be replaced by var_prompt section (prompting user to input)
#                  If having these variables set up in var file is more suitable for you
#                  Please comment out #vars_prompt section
guests:
  - name: Ansible_test #replace by prompt
    ram: 1200 #replace by prompt
    size: 10G #replace by prompt
    vcpus: 2 #replace by prompt
    virt_type: kvm #default
    os:
     os_type: linux #default
     os_variant: rhel6 #default
    swap_space: 1000 #replace by prompt
    root_space: 2000 #replace by prompt
    home_space: 3000 #replace by prompt
    location:
     location_iso: /opt/iso/centos6/CentOS-6.5-x86_64-minimal-Kickstart.iso #recommend having this iso file on the VM host
    ipaddr: 10.10.10.93 #replace by prompt
    vm_waittime_minutes: 5 #replace by prompt
    hostname: ansible.clubmom.local #replace by prompt
    ks_location: http://10.10.30.70/ks/ks-partition.cfg #replace by prompt
    ks_location_local: /var/www/html/ks/ks-partition.cfg #replace by prompt
